### ISSUE TITLE
Doesn't work for "I'm feeling lucky" redirects

### ISSUE THREAD

**Issue by swrobel** [johnnyRose/skip-google-redirects#1]
These are in the form of `https://www.google.com/url?q=https://www.speedtest.net/`

[This Chrome extension](https://chrome.google.com/webstore/detail/redirect-google-redirects/nlacgjiklmjjejlgoclnjhndjaiempdo) handles them well. Here's the code:

```js
var realUrlRegex = /[\?&]q=([^&$]+)/;

chrome.webRequest.onBeforeRequest.addListener(function (details) {
	var redirectMatch = details.url.match(realUrlRegex);

	if (redirectMatch) {
		return { redirectUrl: decodeURIComponent(redirectMatch[1]) };
	}
}, {
	urls: ["*://www.google.com/url*"],
	types: ["main_frame"]
}, ["blocking"]);
```

**Comment by johnnyRose** [comment]
Thank you, I will take a look at this tomorrow!

**Comment by johnnyRose** [comment]
@swrobel - thanks again for reporting! The update is live on AMO. :)
